Repository geoarrow/geoarrow-rs, pull requests merged in 2025-06, with the labels that each got.

#1174 feat(Python): Add GeoArrowArrayReader
  Cargo.lock
  Cargo.toml
  python/Cargo.lock
  python/geoarrow-core/python/geoarrow/rust/core/_array_reader.pyi
  python/geoarrow-core/python/geoarrow/rust/core/_rust.pyi
  python/geoarrow-core/src/lib.rs
  rust/pyo3-geoarrow/src/array_reader.rs
  rust/pyo3-geoarrow/src/lib.rs
Labels: feat

#1178 ci(python): Validate Python docs build without errors
  .github/workflows/python.yml
  python/docs/DEVELOP.md
  python/docs/api/core/geometry/type.md
  python/docs/api/io/geoparquet.md
  python/docs/performance/multithreading.md
  python/geoarrow-compute/python/geoarrow/rust/compute/_compute.pyi
  python/geoarrow-core/python/geoarrow/rust/core/_rust.pyi
  python/geoarrow-io/python/geoarrow/rust/io/_flatgeobuf.pyi
  python/geoarrow-io/python/geoarrow/rust/io/_parquet.pyi
  python/geoarrow-io/python/geoarrow/rust/io/_shapefile.pyi
  python/geoarrow-io/python/geoarrow/rust/io/types.py
  python/mkdocs.yml
Labels: ci

#1180 ci: Turn off failing pyodide io wheel test
  .github/workflows/python.yml
Labels: ci

#1181 feat(python): Stabilize GeoArrowType object
  python/geoarrow-core/python/geoarrow/rust/core/_data_type.pyi
  python/geoarrow-core/python/geoarrow/rust/core/_rust.pyi
  python/geoarrow-core/src/lib.rs
  python/pyproject.toml
  python/tests/core/test_geoarrow_type.py
  python/uv.lock
  rust/pyo3-geoarrow/src/array.rs
  rust/pyo3-geoarrow/src/array_reader.rs
  rust/pyo3-geoarrow/src/chunked_array.rs
  rust/pyo3-geoarrow/src/data_type.rs
  rust/pyo3-geoarrow/src/lib.rs
Labels: feat

#1182 test(Python): Add CRS tests
  python/geoarrow-core/python/geoarrow/rust/core/_chunked_array.pyi
  python/geoarrow-core/python/geoarrow/rust/core/_constructors.pyi
  python/geoarrow-core/python/geoarrow/rust/core/types.py
  python/tests/core/test_crs.py
  python/tests_old/test_crs.py
  rust/pyo3-geoarrow/src/crs.rs
Labels: test

#1184 docs(Python): Show `large_wkb`, `wkb_view`, `large_wkt`, `wkt_view` constructors
  python/docs/api/core/geometry_type.md
  python/geoarrow-core/python/geoarrow/rust/core/_data_type.pyi
Labels: docs

#1185 feat(Python): Implement __eq__ for GeoArrowArray and ChunkedGeoArrowArray
  python/geoarrow-core/python/geoarrow/rust/core/_array.pyi
  python/geoarrow-core/python/geoarrow/rust/core/_chunked_array.pyi
  python/tests/core/test_array.py
  python/tests/core/test_chunked_array.py
  python/tests/core/test_type.py
  rust/pyo3-geoarrow/src/array.rs
  rust/pyo3-geoarrow/src/chunked_array.rs
Labels: feat

#1195 feat(python): Add `AnyGeoArray` for abstracting over either array or stream input
  rust/pyo3-geoarrow/src/array_reader.rs
  rust/pyo3-geoarrow/src/input.rs
  rust/pyo3-geoarrow/src/lib.rs
Labels: feat

#1196 feat(geoarrow-array): Add `GeoArrowArrayReader` trait and `GeoArrowArrayIterator` struct
  rust/geoarrow-array/src/lib.rs
  rust/geoarrow-array/src/trait_.rs
Labels: feat

#1197 chore(python): Refactor to use upstream GeoArrowArrayReader trait
  rust/pyo3-geoarrow/src/array_reader.rs
  rust/pyo3-geoarrow/src/chunked_array.rs
  rust/pyo3-geoarrow/src/input.rs
Labels: chore

#1198 feat(Python): `from_wkb`, `from_wkt`, `to_wkb`, `to_wkt`
  python/geoarrow-core/python/geoarrow/rust/core/_data_type.pyi
  python/geoarrow-core/python/geoarrow/rust/core/_interop.pyi
  python/geoarrow-core/python/geoarrow/rust/core/_rust.pyi
  python/geoarrow-core/src/ffi/to_python/array.rs
  python/geoarrow-core/src/ffi/to_python/mod.rs
  python/geoarrow-core/src/interop/mod.rs
  python/geoarrow-core/src/interop/wkb.rs
  python/geoarrow-core/src/interop/wkt.rs
  python/geoarrow-core/src/lib.rs
  python/geoarrow-core/src/table/geo_interface.rs
  python/geoarrow-core/src/table/mod.rs
  python/tests/core/interop/test_wkb.py
  python/tests/core/interop/test_wkt.py
Labels: feat

#1201 chore: Bump Datafusion to 48
  Cargo.lock
  Cargo.toml
Labels: chore

#1203 chore: Fixes for clippy 1.88
  python/geoarrow-core/src/interop/wkb.rs
  python/geoarrow-core/src/interop/wkt.rs
  python/geoarrow-io/src/input/sync.rs
  python/geoarrow-io/src/parquet/async.rs
  python/geoarrow-io/src/runtime.rs
  rust/geoarrow-array/src/array/geometry.rs
  rust/geoarrow-array/src/array/geometrycollection.rs
  rust/geoarrow-array/src/array/linestring.rs
  rust/geoarrow-array/src/array/mixed.rs
  rust/geoarrow-array/src/array/multilinestring.rs
  rust/geoarrow-array/src/array/multipoint.rs
  rust/geoarrow-array/src/array/multipolygon.rs
  rust/geoarrow-array/src/array/point.rs
  rust/geoarrow-array/src/array/polygon.rs
  rust/geoarrow-array/src/array/rect.rs
  rust/geoarrow-array/src/array/wkb.rs
  rust/geoarrow-array/src/array/wkb_view.rs
  rust/geoarrow-array/src/array/wkt.rs
  rust/geoarrow-array/src/array/wkt_view.rs
  rust/geoarrow-array/src/builder/geo_trait_wrappers.rs
  rust/geoarrow-array/src/builder/linestring.rs
  rust/geoarrow-array/src/builder/point.rs
  rust/geoarrow-array/src/builder/polygon.rs
  rust/geoarrow-array/src/cast.rs
  rust/geoarrow-array/src/geozero/export/data_source/mod.rs
  rust/geoarrow-array/src/geozero/export/scalar/coord.rs
  rust/geoarrow-array/src/geozero/export/scalar/point.rs
  rust/geoarrow-cast/src/cast.rs
  rust/geoarrow-geos/src/export/scalar/coord.rs
  rust/geoarrow-schema/src/datatype.rs
  rust/geoarrow-schema/src/dimension.rs
  rust/geoarrow-schema/src/type.rs
  rust/geodatafusion/src/data_types.rs
  rust/geoparquet/src/metadata.rs
  rust/geoparquet/src/reader/geo_ext.rs
  rust/geoparquet/src/reader/metadata.rs
  rust/geoparquet/src/reader/parse.rs
  rust/geoparquet/src/reader/spatial_filter.rs
  rust/geoparquet/src/writer/metadata.rs
  rust/pyo3-geoarrow/src/coord_buffer.rs
Labels: chore

#1204 chore(Python): Bump to 0.4.0-beta.5
  Cargo.lock
  python/Cargo.lock
  python/Cargo.toml
Labels: chore

#1025 feat(geoarrow-geo): Initial geoarrow-geo crate using `ArrayAccessor` trait
  Cargo.lock
  Cargo.toml
  rust/geoarrow-geo/Cargo.toml
  rust/geoarrow-geo/README.md
  rust/geoarrow-geo/src/area.rs
  rust/geoarrow-geo/src/convex_hull.rs
  rust/geoarrow-geo/src/lib.rs
  rust/geoarrow-geo/src/simplify.rs
Labels: feat

#1206 fix(geoarrow-array): inconsistencies between code and comment
  rust/geoarrow-array/src/array/coord/interleaved.rs
  rust/geoarrow-array/src/trait_.rs
Labels: fix
