Repository geoarrow/geoarrow-rs, pull requests merged in 2025-07, with the labels that each got.

#1211 chore(python): Prepare for 0.4.0 release
  python/CHANGELOG.md
  python/Cargo.lock
  python/Cargo.toml
  python/docs/api/core/geometry/scalar.md
  python/mkdocs.yml
Labels: chore

#1215 fix(Python): Fix exporting CRS to Pyproj for GeoArrow 0.1 metadata
  rust/pyo3-geoarrow/src/crs.rs
Labels: fix

#1221 chore(geoparquet): prepare for 0.4 release
  CHANGELOG.md
Labels: chore

#1222 fix(geoparquet): Fix crate publish for 0.4
  rust/geoparquet/src/writer/encode.rs
Labels: fix

#1227 feat(geoarrow-geo): add intersects function
  rust/geoarrow-geo/src/intersects.rs
  rust/geoarrow-geo/src/lib.rs
  rust/geoarrow-geo/src/util/downcast.rs
  rust/geoarrow-geo/src/util/mod.rs
Labels: feat

#1228 feat(geodatafusion): ST_CoordDim and ST_NDims UDFs
  rust/geodatafusion/Cargo.toml
  rust/geodatafusion/README.md
  rust/geodatafusion/src/udf/native/accessors/coord_dim.rs
  rust/geodatafusion/src/udf/native/accessors/mod.rs
  rust/geodatafusion/src/udf/native/mod.rs
Labels: feat

#1229 feat(geodatafusion): ST_Area
  Cargo.lock
  Cargo.toml
  rust/geodatafusion/Cargo.toml
  rust/geodatafusion/README.md
  rust/geodatafusion/src/udf/native/accessors/coord_dim.rs
  rust/geodatafusion/src/udf/native/measurement/area.rs
  rust/geodatafusion/src/udf/native/measurement/mod.rs
  rust/geodatafusion/src/udf/native/mod.rs
Labels: feat

#1232 feat(geodatafusion): Add `ST_Intersects`
  Cargo.lock
  rust/geodatafusion/Cargo.toml
  rust/geodatafusion/src/udf/geo/mod.rs
  rust/geodatafusion/src/udf/geo/relationships/mod.rs
  rust/geodatafusion/src/udf/geo/relationships/topological/intersects.rs
  rust/geodatafusion/src/udf/geo/relationships/topological/mod.rs
  rust/geodatafusion/src/udf/mod.rs
Labels: feat

#1233 feat(geodatafusion): Implement topological relationships
  rust/geoarrow-geo/src/lib.rs
  rust/geoarrow-geo/src/relate.rs
  rust/geoarrow-geo/src/util/downcast.rs
  rust/geodatafusion/README.md
  rust/geodatafusion/src/udf/geo/mod.rs
  rust/geodatafusion/src/udf/geo/relationships/mod.rs
  rust/geodatafusion/src/udf/geo/relationships/topological/mod.rs
  rust/geodatafusion/src/udf/geo/relationships/topological/relate.rs
Labels: feat

#1057 feat(flatgeobuf): Restore the `FlatGeobuf` reader
  Cargo.lock
  Cargo.toml
  rust/geoarrow-flatgeobuf/Cargo.toml
  rust/geoarrow-flatgeobuf/src/lib.rs
  rust/geoarrow-flatgeobuf/src/reader/async.rs
  rust/geoarrow-flatgeobuf/src/reader/common.rs
  rust/geoarrow-flatgeobuf/src/reader/mod.rs
  rust/geoarrow-flatgeobuf/src/reader/object_store_reader.rs
  rust/geoarrow-flatgeobuf/src/reader/sync.rs
  rust/geoarrow-flatgeobuf/src/reader/table_builder.rs
  rust/geoarrow-old/src/io/flatgeobuf/mod.rs
  rust/geoarrow-old/src/io/flatgeobuf/reader/async.rs
  rust/geoarrow-old/src/io/flatgeobuf/reader/common.rs
  rust/geoarrow-old/src/io/flatgeobuf/reader/mod.rs
  rust/geoarrow-old/src/io/flatgeobuf/reader/sync.rs
  rust/geoparquet/Cargo.toml
Labels: feat

#1235 feat: contains fn
  rust/geoarrow-geo/src/contains.rs
  rust/geoarrow-geo/src/lib.rs
Labels: feat

#1239 feat(geodatafusion): Allow loading WKB from BinaryView columns
  rust/geodatafusion/src/udf/native/io/wkb.rs
Labels: feat

#1241 fix(geoarrow-geo): Fix compilation error when converting geo-traits to `geo` geometries
  Cargo.lock
  Cargo.toml
  rust/geoarrow-geo/src/area.rs
  rust/geoarrow-geo/src/centroid.rs
  rust/geoarrow-geo/src/contains.rs
  rust/geoarrow-geo/src/convex_hull.rs
  rust/geoarrow-geo/src/intersects.rs
  rust/geoarrow-geo/src/lib.rs
  rust/geoarrow-geo/src/relate.rs
  rust/geoarrow-geo/src/util/mod.rs
  rust/geoarrow-geo/src/util/to_geo.rs
  rust/geoarrow-old/src/io/geo.rs
  rust/geodatafusion/src/udf/geo/relationships/topological/intersects.rs
  rust/geodatafusion/src/udf/geo/relationships/topological/relate.rs
Labels: fix

#1246 feat(python): Add `path` property to GeoParquetFile
  python/geoarrow-io/python/geoarrow/rust/io/_parquet.pyi
  python/geoarrow-io/src/parquet/async.rs
  python/tests/io/test_parquet.py
Labels: feat

#1248 chore(geodatafusion): Upgrade to DataFusion 49.0.0
  Cargo.lock
  Cargo.toml
  rust/geodatafusion/src/error.rs
Labels: chore

#1253 feat(geodatafusion): ST_Centroid and ST_ConvexHull
  rust/geoarrow-geo/src/convex_hull.rs
  rust/geodatafusion/src/udf/geo/mod.rs
  rust/geodatafusion/src/udf/geo/processing/centroid.rs
  rust/geodatafusion/src/udf/geo/processing/convex_hull.rs
  rust/geodatafusion/src/udf/geo/processing/mod.rs
  rust/geodatafusion/src/udf/native/processing/centroid.rs
  rust/geodatafusion/src/udf/native/processing/convex_hull.rs
Labels: feat

#1256 feat(geodatafusion): Update ST_GeoHash, ST_Box2dFromGeoHash, ST_PointFromGeoHash from old code
  rust/geodatafusion-flatgeobuf/src/lib.rs
  rust/geodatafusion/src/udf/geo/measurement/area.rs
  rust/geodatafusion/src/udf/geo/measurement/mod.rs
  rust/geodatafusion/src/udf/geo/processing/centroid.rs
  rust/geodatafusion/src/udf/geohash/box2d_from_geohash.rs
  rust/geodatafusion/src/udf/geohash/geohash.rs
  rust/geodatafusion/src/udf/geohash/mod.rs
  rust/geodatafusion/src/udf/geohash/point_from_geohash.rs
  rust/geodatafusion/src/udf/mod.rs
  rust/geodatafusion/src/udf/native/constructors/point.rs
  rust/geodatafusion/src/udf/native/io/geohash.rs
  rust/geodatafusion/src/udf/native/measurement/centroid.rs
  rust/geodatafusion/src/udf/native/measurement/mod.rs
  rust/geodatafusion/src/udf/native/mod.rs
Labels: feat

#1259 fix(geodatafusion): Fix input field of ST_Extent
  rust/geodatafusion/src/udf/native/bounding_box/extent.rs
Labels: fix
