Repository geoarrow/geoarrow-rs, pull requests merged in 2025-08, with the labels that each got.

#1260 feat(geoarrow-flatgeobuf): Improved schema inference & expose more from header
  Cargo.lock
  rust/geoarrow-flatgeobuf/Cargo.toml
  rust/geoarrow-flatgeobuf/src/lib.rs
  rust/geoarrow-flatgeobuf/src/reader/async.rs
  rust/geoarrow-flatgeobuf/src/reader/common.rs
  rust/geoarrow-flatgeobuf/src/reader/mod.rs
  rust/geoarrow-flatgeobuf/src/reader/object_store.rs
  rust/geoarrow-flatgeobuf/src/reader/schema.rs
  rust/geoarrow-flatgeobuf/src/reader/sync.rs
  rust/geoarrow-flatgeobuf/src/writer.rs
  rust/geodatafusion-flatgeobuf/src/file_format.rs
Labels: feat

#1261 chore(geoarrow-flatgeobuf): update flatgeobuf dep to 5.0
  Cargo.lock
  Cargo.toml
Labels: chore

#1269 fix(geoarrow-array): Allow pushing Rect to MultiPolygonBuilder
  rust/geoarrow-array/src/builder/multipolygon.rs
Labels: fix

#1270 feat(geoarrow-geos, geoarrow-array): Remove unneeded todos
  rust/geoarrow-array/src/array/geometry.rs
  rust/geoarrow-array/src/array/point.rs
  rust/geoarrow-geos/src/export/scalar/coord.rs
  rust/geoarrow-geos/src/import/scalar/polygon.rs
Labels: feat

#1271 fix(geoarrow-array)!: WkbBuilder should return result when appending geometries
  rust/geoarrow-array/src/array/wkb.rs
  rust/geoarrow-array/src/builder/wkb.rs
  rust/geoarrow-array/src/cast.rs
  rust/geoarrow-geos/src/import/array/wkb.rs
Labels: fix, breaking change

#1273 chore(geodatafusion): Use datafusion git pin on main to support Arrow 56
  Cargo.lock
  Cargo.toml
Labels: chore

#1278 feat(geodatafusion): Add aliases for WKT and WKB functions
  rust/geodatafusion/README.md
  rust/geodatafusion/src/data_types.rs
  rust/geodatafusion/src/udf/native/io/wkb.rs
  rust/geodatafusion/src/udf/native/io/wkt.rs
Labels: feat

#1279 feat(python, geoarrow-rust-io): Add `read_flatgeobuf`, `read_flatgeobuf_async`, `write_flatgeobuf`
  python/Cargo.lock
  python/Cargo.toml
  python/docs/api/io/flatgeobuf.md
  python/geoarrow-io/Cargo.toml
  python/geoarrow-io/python/geoarrow/rust/io/_flatgeobuf.pyi
  python/geoarrow-io/python/geoarrow/rust/io/_io.pyi
  python/geoarrow-io/src/error.rs
  python/geoarrow-io/src/flatgeobuf/async.rs
  python/geoarrow-io/src/flatgeobuf/mod.rs
  python/geoarrow-io/src/flatgeobuf/sync.rs
  python/geoarrow-io/src/flatgeobuf/utils.rs
  python/geoarrow-io/src/input/mod.rs
  python/geoarrow-io/src/input/sync.rs
  python/geoarrow-io/src/io/flatgeobuf/async.rs
  python/geoarrow-io/src/io/flatgeobuf/sync.rs
  python/geoarrow-io/src/lib.rs
  python/mkdocs.yml
  python/tests/io/test_flatgeobuf.py
  rust/geoarrow-flatgeobuf/src/reader/README.md
  rust/geoarrow-flatgeobuf/src/reader/common.rs
  rust/geoarrow-flatgeobuf/src/reader/object_store.rs
  rust/geoarrow-flatgeobuf/src/reader/schema.rs
  rust/geodatafusion-flatgeobuf/src/file_format.rs
  rust/geodatafusion-flatgeobuf/src/lib.rs
  rust/geodatafusion-flatgeobuf/src/source.rs
Labels: feat

#1281 fix(geoarrow-python-io): Release GIL when blocking tokio runtime
  python/geoarrow-io/src/flatgeobuf/sync.rs
  python/geoarrow-io/src/parquet/async.rs
  python/geoarrow-io/src/parquet/sync.rs
Labels: fix

#1285 test(geoarrow-flatgeobuf): More tests for FlatGeobuf writer
  python/geoarrow-io/src/flatgeobuf/sync.rs
  rust/geoarrow-flatgeobuf/src/writer.rs
Labels: test

#1288 chore(python): Bump to 0.5.0-beta.1
  python/Cargo.lock
  python/Cargo.toml
Labels: chore

#1291 chore(python): Bump to 0.5.0-beta.2
  python/Cargo.lock
  python/Cargo.toml
Labels: chore

#1293 chore: Prepare 0.5 release
  Cargo.lock
  Cargo.toml
  README.md
  docs/mkdocs.yml
  python/README.md
  rust/README.md
  rust/geoarrow-array/CHANGELOG.md
  rust/geoarrow-cast/CHANGELOG.md
  rust/geoarrow-flatgeobuf/CHANGELOG.md
  rust/geoarrow-schema/CHANGELOG.md
  rust/geoparquet/CHANGELOG.md
Labels: chore

#1294 chore: Prepare Python 0.5.0 release
  docs/README.md
  python/CHANGELOG.md
  python/Cargo.lock
  python/Cargo.toml
Labels: chore

#1299 feat(geodatafusion): `Box3D`, `ST_ZMin`, `ST_ZMax` UDFs
  rust/geodatafusion/README.md
  rust/geodatafusion/src/udf/native/bounding_box/box.rs
  rust/geodatafusion/src/udf/native/bounding_box/box_2d.rs
  rust/geodatafusion/src/udf/native/bounding_box/extent.rs
  rust/geodatafusion/src/udf/native/bounding_box/extrema.rs
  rust/geodatafusion/src/udf/native/bounding_box/mod.rs
  rust/geodatafusion/src/udf/native/bounding_box/util/bounds.rs
  rust/geodatafusion/src/udf/native/io/wkt.rs
Labels: feat

#1305 ci: Build Python 3.13 wheels on Windows
  .github/workflows/python-core-wheels.yml
  .github/workflows/python-docs.yml
  .github/workflows/python-io-wheels.yml
  .github/workflows/python.yml
Labels: ci

#1301 feat: add FlatGeobuf sink for DataFusion
  Cargo.lock
  Cargo.toml
  rust/geoarrow-array/CHANGELOG.md
  rust/geoarrow-array/src/builder/linestring.rs
  rust/geoarrow-array/src/builder/multilinestring.rs
  rust/geoarrow-array/src/builder/multipoint.rs
  rust/geoarrow-array/src/builder/multipolygon.rs
  rust/geoarrow-array/src/builder/polygon.rs
  rust/geoarrow-array/src/geozero/export/data_source/mod.rs
  rust/geoarrow-array/src/geozero/export/data_source/record_batch.rs
  rust/geoarrow-array/src/geozero/export/data_source/record_batch_reader.rs
  rust/geoarrow-array/src/geozero/export/mod.rs
  rust/geoarrow-flatgeobuf/CHANGELOG.md
  rust/geoarrow-flatgeobuf/src/writer.rs
  rust/geodatafusion-flatgeobuf/Cargo.toml
  rust/geodatafusion-flatgeobuf/src/file_format.rs
  rust/geodatafusion-flatgeobuf/src/lib.rs
Labels: feat, codex

#1295 feat(geodatafusion-flatgeobuf): Enable bounding box pushdown for FlatGeobuf scans
  rust/geodatafusion-flatgeobuf/Cargo.toml
  rust/geodatafusion-flatgeobuf/src/lib.rs
  rust/geodatafusion-flatgeobuf/src/source.rs
  rust/geodatafusion/src/udf/native/bounding_box/mod.rs
  rust/geodatafusion/src/udf/native/bounding_box/util/bounds.rs
  rust/geodatafusion/src/udf/native/bounding_box/util/mod.rs
Labels: feat, codex

#1040 feat(geoarrow-geojson): GeoJSON writer using arrow-json's new custom encoders
  Cargo.lock
  Cargo.toml
  rust/geoarrow-array/src/builder/multilinestring.rs
  rust/geoarrow-array/src/builder/multipolygon.rs
  rust/geoarrow-array/src/builder/polygon.rs
  rust/geoarrow-geojson/Cargo.toml
  rust/geoarrow-geojson/README.md
  rust/geoarrow-geojson/src/encoder/factory.rs
  rust/geoarrow-geojson/src/encoder/geometry.rs
  rust/geoarrow-geojson/src/encoder/geometrycollection.rs
  rust/geoarrow-geojson/src/encoder/linestring.rs
  rust/geoarrow-geojson/src/encoder/mod.rs
  rust/geoarrow-geojson/src/encoder/multilinestring.rs
  rust/geoarrow-geojson/src/encoder/multipoint.rs
  rust/geoarrow-geojson/src/encoder/multipolygon.rs
  rust/geoarrow-geojson/src/encoder/point.rs
  rust/geoarrow-geojson/src/encoder/polygon.rs
  rust/geoarrow-geojson/src/encoder/rect.rs
  rust/geoarrow-geojson/src/encoder/wkb.rs
  rust/geoarrow-geojson/src/encoder/wkt.rs
  rust/geoarrow-geojson/src/lib.rs
  rust/geoarrow-geojson/src/writer/mod.rs
Labels: feat

#1309 feat(geodatafusion-geojson): Add GeoJSON table provider to write to line-delimited GeoJSON
  Cargo.lock
  Cargo.toml
  rust/geodatafusion-geojson/Cargo.toml
  rust/geodatafusion-geojson/src/file_format.rs
  rust/geodatafusion-geojson/src/lib.rs
Labels: feat

#1251 feat(geodatafusion): Smallest POC for reading GeoParquet into DataFusion
  Cargo.lock
  Cargo.toml
  rust/geodatafusion-geoparquet/Cargo.toml
  rust/geodatafusion-geoparquet/README.md
  rust/geodatafusion-geoparquet/src/file_format.rs
  rust/geodatafusion-geoparquet/src/lib.rs
  rust/geodatafusion-geoparquet/src/source.rs
  rust/geoparquet/CHANGELOG.md
  rust/geoparquet/src/reader/mod.rs
  rust/geoparquet/src/reader/parse.rs
Labels: feat

#1308 feat(geoarrow-geo): Add support for ST_length
  rust/geoarrow-geo/src/length.rs
  rust/geoarrow-geo/src/lib.rs
Labels: feat

#1313 perf(geoarrow-array): Improve perf of `from_wkb`/`from_wkt` when parsing to WKB/WKT output types
  Cargo.lock
  rust/geoarrow-array/CHANGELOG.md
  rust/geoarrow-array/src/cast.rs
Labels: perf
